server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.52.130:1111 #linux nagix端口
management:
  endpoints:
    web:
      exposure:
        include: '*'