server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:/config

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
